.gitignore, bower.json, demo/index.html, index.html, iron-autogrow-textarea.html, test/basic.html, test/index.html
:fire: 
For the record, this looked like this for most of today, and I wasn't even mad:
=> Bring autogrow-textarea to the future

iron-autogrow-textarea.html
The mixin doesn't seem to work when the textarea is used inside a `paper-input-container`, but I don't understand why. In any case, using the class fixes it.
:point_right: @cdata @morethanreal
=> Use layout classes instead of mixin

bower.json, demo/index.html, index.html, iron-autogrow-textarea.html, test/basic.html
This is simpler and paper-input-container can treat this element
as a custom input, instead of requiring special handling for
the split responsibilies between the textarea and the sizer.
textarea API is available via the textarea() getter.
@notwaldorf PTAL cc @cdata
=> include textarea in local dom

bower.json, iron-autogrow-textarea.html, test/basic.html
To make this work in an `iron-form` correctly (https://github.com/PolymerElements/iron-form/issues/12):
- added the `iron-form-element-behaviour` and a `value` property, to be used in serializing. It just mirrors `bind-value`, which I think is vestigial property naming from the days when this element was actually a `<textarea is="iron-textarea">`
- added a `validate()` method, mirrored after `iron-input`. Since `iron-autogrow-textarea` almost never has a validator set, it wasn't really getting validated at all.
The only reason why the `iron-autogrow-textarea` cared about `name` is because it magically worked in an `iron-form`. However, since it's a custom element, we process it's value separately, and don't need to pass it down to the `textarea`. If we do pass it down to the `textarea` …
=> fix broken behaviour when included in an iron-form

iron-autogrow-textarea.html
`textarea` should inherit `line-height` in order to grow precisely
=> inherit line-height

iron-autogrow-textarea.html
When building a binary using Crisper this caused issues since the next code was wrapped in parens a-la
```
(function() { foo; })();
```
which ultimately called the iron-autogrow-textarea constructor, causing an exception.
=> Adds a semicolon after the Polymer call.

iron-autogrow-textarea.html
According to [W3C](http://www.w3.org/TR/html5/forms.html#attr-fe-autofocus), `autofocus` is a boolean attribute. Using "off" as default value, the `textarea` is actually with `autofocus`. The default value should be boolean false to prevent default autofocus behavior.
Fixes #17
=> Define autofocus as boolean property

iron-autogrow-textarea.html
Previously, `_onInput` called `_update` after setting `bindValue`. But setting `bindValue` triggers `_bindValueChanged`, which calls `_update` too, so it's called twice.
After removing the call from `_onInput`, there was only one callsite left (and I assume that no other files use it), so I inlined `_update` (minus a now unnecessary check).
=> Remove _update & inline into _bindValueChanged

iron-autogrow-textarea.html, test/basic.html
:balloon: @cdata 
I don't think `selectionStart` is accessible as an attribute, so I've added getters/setters to pass it down to the textarea. It's needed to make the `paper-input` tests pass (see https://github.com/PolymerElements/paper-input/pull/151)
=> make selectionStart and selectionEnd work

iron-autogrow-textarea.html
Added an attribute to the textarea to pass the disabled state of iron-autogrow-textarea.
Without this, the textarea is still focusable via javascript.
=> Bind disabled attribute

iron-autogrow-textarea.html
Fixes https://github.com/PolymerElements/iron-autogrow-textarea/issues/39
Double-updating the underlying textarea's value has no effect on desktop. However, on swipe keyboards, the final value isn't actually committed when we update it like this, so we lose un-committed words.
/cc @azakus
=> fix double saving of values

iron-autogrow-textarea.html, test/basic.html
Fixes https://github.com/PolymerElements/iron-autogrow-textarea/issues/37
(and matches `iron-input`'s logic in `_bindValueChanged`)
=> treat undefined like the empty string

iron-autogrow-textarea.html
Needed by https://github.com/PolymerElements/paper-input/pull/216
This fix allows textarea's <code>text-align</code> to be inherited.
=> text-align inherited for shadow dom case

iron-autogrow-textarea.html
Fixes https://github.com/PolymerElements/iron-autogrow-textarea/issues/47
=> use xhtml friendly spaces

iron-autogrow-textarea.html
Fixes https://github.com/PolymerElements/iron-autogrow-textarea/issues/70
Before this PR, when setitng a max-height, the cursor could be drawn outside the element, which isn't great:
This fixes that.
=> fix drawing outside the border

iron-autogrow-textarea.html
Hi,
I noticed some differences between the value semantics of ```iron-input``` and ```iron-autogrow-textarea```.
* ```bindValue``` should not have a type definition of  ```{string|number|undefined|null}```. Cant think of a reason why one should allow other type than string here. This makes input validation unnecessarily complex.
* The default value for HTML-inputs and textareas is an empty string ```''``` instead of ```undefined```
* Adding ```ready``` to update ```bindValue```, this is related to https://github.com/PolymerElements/iron-input/issues/76. It fixes validation errors. JSBIN: http://jsbin.com/vetiwupele/1/edit?html,output .
Also see https://github.com/PolymerElements/paper-input/pull/315 .
=> make value semantic more similar to iron-input

iron-autogrow-textarea.html
`<paper-input>` gets appropriate color styling to its native `input` element's placeholder.
https://github.com/PolymerElements/paper-input/blob/master/paper-input.html#L77-L91
`<paper-textarea>` doesn't because `<iron-autogrow-textarea>` doesn't support it. 
In order to spread the placeholder color love to `<paper-textarea>`, we need some mixins to get down and dirty with the native `textarea` element.
=> Added mixin to style placeholder

iron-autogrow-textarea.html
Later on in the code we check to see if `this.bindValue === 0` which only makes sense if it can sometimes be a number
=> Document that bindValue could be string or number

iron-autogrow-textarea.html, test/basic.html
Fixes https://github.com/PolymerElements/iron-autogrow-textarea/issues/33
This is part of a 3-headed hydra of PRs that is trying to fix the following problem: `iron-form` was bad at de-duping nested elements with the same `name`, and would double submit them. The problem was that if you bind the `name` attribute all the way down, and these children you're binding it to are either native elements (so the form automatically cares about them) or custom elements with the `IronFormElementBehavior`, you would submit the same value twice.
To get around this, `paper-textarea` had a cheat where it wouldn't implement `IronFormElementBehavior`, its child, the `iron-autogrow-textarea` would, but to make sure that the nested `textarea` also didn't double submit, it didn't pass the `name` all the way …
=> Clean up `value` inherited form IronFormElementBehavior

iron-autogrow-textarea.html
Fixes https://github.com/PolymerElements/paper-input/issues/468
TL;DR: iOS has a rando 3px margin-left that no other browser has, which means, say, if you're trying to position the `paper-textarea`'s label in a sane place, the cursor is going to overlap it and you're going to have a bad time.
Before this PR:
After this PR:
(the after now matches what we saw in Chrome/Safari/FF normally, which stays unchanged)
=> Fix non-standard iOS-only margin-left

.gitignore, README.md, bower.json, demo/index.html, iron-autogrow-textarea.html, test/index.html
Notable changes:
- `bindValue` was marked as deprecated, said to use `value` instead, but `value` wasn't defined and `bindValue` was still doing all the heavy lifting. Also, in 2.0 if you don't declare a property you don't serialize to it either, so anyway, cleaned this up.
- made `value`/`bindValue` be a notifying property vs fire the `foo-changed` event manually. It's currently broken in 2.0 and I'm not 100% sure if we need it anymore, since the long-ago days when `iron-autogrow-textarea` stopped being a type extension.
- cleaned up the `validate` code to match that of `iron-input`, and have the correct behaviour of using the native validity first. I think that's correct and not a giant breaking change
=> 2.0 preview

iron-autogrow-textarea.html
Plumb label property through as aria-label to give internal textarea an accessible name.
=> Expose label prop for aria-label

iron-autogrow-textarea.html
When different styles are added to the textarea (ex: white-space: pre),
the mirror no longer accurately represents the height of the textarea.
In order to fix this, apply the mixin  styles applied to the textarea
to the mirror also.
=> Add mixin properties to mirror

iron-autogrow-textarea.html
This is still needed in paper-input/paper-input-container.html (L513 of paper-input-v2.0.1)
Fixes PolymerElements/paper-input#508
The event listened to is "hidden" behind `_valueChangedEvent`, which returns `bind-value-changed` by default ([GitHub link](/PolymerElements/paper-input/blob/v2.0.1/paper-input-container.html#L513))
=> re-enable `bind-value-changed` event

.travis.yml, iron-autogrow-textarea.d.ts, iron-autogrow-textarea.html, package-lock.json, package.json, test/basic.html, test/index.html
Runs the experimental autoformatter [webmat](https://github.com/PolymerLabs/webmat) which runs clang-format on js files and makes it so that it can run on HTML files. Please look through this PR with `?w=1` in the diff to make sure that no logic was changed.
What has changed?
You can run the formatter on the whole project by running `npm run format` and ex/include files from the formatter, and enter your custom clang-format config in a formatconfig.json see webmat readme for more
=> Automatic format!

iron-autogrow-textarea.js
The `textarea` does not support `autocapitalize`.
This adds this attribute as per the spec:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea#Attributes
=> Add missing autocapitalize attribute

iron-autogrow-textarea.js
In TypeScript 3.8 a new property `autofocus` was introduced on `HTMLElement`. When this component extends `HTMLElement` the `autofocus` properties now conflict. This change marks `autofocus` as non-nullable to align with TypeScript's `HTMLElement`.
Here's a playground link demoing the issue: http://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgCoQB5gIJQnAYQHsBbAByJAnGU0hABMBnZACVQFkAZAUQBsIJamGQBvAFDIpyOAFcwRGEQSymALmQAjIkQFwQyAD7IQsvnyPJZjCDFAQGAbnEBfcUA
To see past behavior set the version to 3.7.5, and the current by setting the version to 3.8.3.
=> Update autofocus property to be non-nullable

iron-autogrow-textarea.html
This patch was only necessary for iOS 12 and below, hence this fix.
=> Fix iOS 13 margin
